import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ReactQueryClientProvider } from "@/src/utils/queryProvider";
import { useState } from 'react'
import theme from "@/src/theme";
import "./globals.css";

export const metadata: Metadata = {
  title: "Responder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
    <html lang="en">
      <body>
        <AppRouterCacheProvider theme={theme}>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
    </ReactQueryClientProvider>
  );
}
